---
html_document: default
author: "Sheetal M"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
title: "assignment_08-09_MunjewarSheetal-01"
word_document: default
link-citations: yes
---

## Install and Load required packages :
```{r, echo=TRUE}

# Package names
# packages <- c("ggplot2","dplyr","tidyr","magrittr","tidyverse","purrr")
packages <- c("ggplot2","dplyr","magrittr","tidyverse","purrr","pander","pandoc")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```

``` {r}

## Set the working directory to the root of your DSC 520 directory
setwd("E:\\Data_Science_DSC510\\DSC520-Statistics\\dsc520") 

## Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("data/r4ds/heights.csv")
# nrow(heights_df)
## Load the ggplot2 library
library(ggplot2)

## Fit a linear model using the `age` variable as the predictor and `earn` as the outcome
age_lm <- lm(heights_df$earn ~ heights_df$age, data = heights_df)

## View the summary of your model using `summary()`
summary(age_lm)
# plot(age_lm)

```

## Creating predictions using `predict()`
```{r}

#str(heights_df)
#mt_age <- data.frame(heights_df$age)
age_predict_df <- data.frame(earn = predict(age_lm, heights_df), age=heights_df$age)
plot(age_predict_df)

# - Reference https://www.youtube.com/watch?v=rfH7pCFvFT0 ( Linear Regression )
ggplot(data = heights_df, aes(x = heights_df$age, y = heights_df$earn)) +
  geom_point(color='blue') +
  geom_line(color='red',data = age_predict_df, aes(x=age_predict_df$age, y=age_predict_df$earn))


#ggplot(data = heights_df, aes(x = heights_df$age, y = heights_df$earn)) +
#  geom_point(color='blue') +
#  geom_smooth(method = "lm") + 
#  geom_line(color='red',data = age_predict_df, aes(x=age_predict_df$age, y=age_predict_df$earn)) +
#  geom_smooth(method = "lm")

```

```{r, echo=TRUE}

mean_earn <- mean(heights_df$earn)

## Corrected Sum of Squares Total
sst <- sum((mean_earn - heights_df$earn)^2)

## Corrected Sum of Squares for Model
ssm <- sum((mean_earn - age_predict_df$earn)^2)

## Residuals
residuals <- heights_df$earn - age_predict_df$earn

## Sum of Squares for Error
sse <- sum(residuals^2)

## R Squared R^2 = SSM\SST
r_squared <- ssm / sst

## Number of observations
n <- 1192

## Number of regression parameters
p <- 2

## Corrected Degrees of Freedom for Model (p-1)
dfm <- (p-1)

## Degrees of Freedom for Error (n-p)
dfe <- (n-p)

## Corrected Degrees of Freedom Total:   DFT = n - 1
dft <- n-1

## Mean of Squares for Model:   MSM = SSM / DFM
msm <- ssm/dfm

## Mean of Squares for Error:   MSE = SSE / DFE
mse <- sse/dfe

## Mean of Squares Total:   MST = SST / DFT
mst <- sst/dft

## F Statistic F = MSM/MSE
f_score <- msm/mse

## Adjusted R Squared R2 = 1 - (1 - R2)(n - 1) / (n - p)
adjusted_r_squared <-  1 - (1 - r_squared)*(n - 1) / (n - p) 

## Calculate the p-value from the F distribution
p_value <- pf(f_score, dfm, dft, lower.tail=F)

```